# version: '3.7'

# services:
#   kratos-migrate:
#     image: oryd/kratos:v1.3.1
#     environment:
#       - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
#     depends_on:
#       - postgres
#     command: migrate sql -e --yes

#   kratos:
#     image: oryd/kratos:v1.3.1
#     environment:
#       - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
#     depends_on:
#       - kratos-migrate
#     volumes:
#       - ./kratos:/etc/config/kratos
#     command: serve --dev
#     ports:
#       - "4433:4433" # Public API
#       - "4434:4434" # Admin API

#   hydra-migrate:
#     image: oryd/hydra:v2.3.0
#     environment:
#       - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
#     depends_on:
#       - postgres
#     command: migrate sql -e --yes

#   hydra:
#     image: oryd/hydra:v2.3.0
#     environment:
#       - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
#       - URLS_LOGIN=http://localhost:3000/login
#       - URLS_CONSENT=http://localhost:3000/consent
#       - URLS_LOGOUT=http://localhost:3000/logout
#     depends_on:
#       - hydra-migrate
#     command: serve all --dangerous-force-http
#     ports:
#       - "4444:4444" # Public API
#       - "4445:4445" # Admin API

#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: secret
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
    depends_on:
      - postgres
    command: migrate sql -e --yes

  kratos:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable
    volumes:
      - ./kratos:/etc/config/kratos
    command: serve --dev
    ports:
      - "4433:4433" # Public API
      - "4434:4434" # Admin API
    depends_on:
      - kratos-migrate

  hydra-migrate:
    image: oryd/hydra:v2.3.0
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
    depends_on:
      - postgres
    command: migrate sql -e --yes

  hydra:
    image: oryd/hydra:v2.3.0
    environment:
      - DSN=postgres://hydra:secret@postgres:5432/hydra?sslmode=disable
      - URLS_LOGIN=http://localhost:3000/login
      - URLS_CONSENT=http://localhost:3000/consent
      - URLS_LOGOUT=http://localhost:3000/logout
    depends_on:
      - hydra-migrate
    command: serve all --dangerous-force-http
    ports:
      - "4444:4444" # Public API
      - "4445:4445" # Admin API

volumes:
  postgres_data:
