dsn: postgres://hydra:secret@postgres:5432/hydra?sslmode=disable

urls:
  self:
    issuer: http://localhost:4444/
  consent: http://localhost:3000/consent
  login: http://localhost:3000/login
  logout: http://localhost:3000/logout
