version: v1.3.1

dsn: postgres://kratos:secret@postgres:5432/kratos?sslmode=disable

identity:
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/

  flows:
    login:
      ui_url: http://localhost:3000/login
    registration:
      ui_url: http://localhost:3000/register

  methods:
    password:
      enabled: true

log:
  level: debug
  format: text

secrets:
  cookie:
    - super-secret-cookie-key

courier:
  smtp:
    connection_uri: smtp://user:password@smtp.example.com:587/
